Add lucashi fact
Caelink/lucashifacts pull request #35
Opened 2017-07-07 01:56 UTC by tituschow

pls

2017-07-07 01:57 UTC, Caelink requested changes

2017-07-07 01:57 UTC, Caelink commented on assets/lucashifacts
> +lucashi walked into the fridge door completely sober
pls add to end of file

2017-07-07 01:58 UTC, Hazematman requested changes
Needs more details

2017-07-07 02:00 UTC, Hazematman requested changes
all over himself*

2017-07-07 02:01 UTC, Caelink requested changes

2017-07-07 02:01 UTC, Caelink commented on assets/lucashifacts
> +lucashi walked into the fridge door completely sober and spilled vegetables over himself
`on himself` or `all over himself` pls

2017-07-07 02:46 UTC, Caelink approved these changes

2017-07-16 23:42 UTC, Hazematman approved these changes

2017-07-16 23:43 UTC, merged